# Generated by Django 5.2.9 on 2025-12-16 20:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bem',
            name='data_aquisicao',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='numero_serie',
        ),
        migrations.AddField(
            model_name='bem',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 16, 20, 12, 20, 421113, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bem',
            name='tombo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='status',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='endereco',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bem',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bem',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bens', to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
